//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public int ID { get; set; }
        public string RMusicName { get; set; }
        public System.DateTime RMusicStart { get; set; }
        public System.DateTime RMusicEnd { get; set; }
        public int CateID { get; set; }
        public bool SongOrMusic { get; set; }
        public int OldWeekRankId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
